### ISSUE TITLE
Document that any custom property being observed must had been set before observer

### ISSUE THREAD

**Issue by n0099** [LeaVerou/style-observer#133]
https://jsfiddle.net/fkws0v7c/50/
```html
<main>
  <div class="padding">Scroll down or hover on the gray zone:</div>
  <div class="item sticky"><p></p></div>
</main>
```
```css
main {
  height: 200vh;
}
.padding {
  height: 10vh;
}

.item {
  background: darkgray;
  height: 50vh;
}
.item, .item.sticky > p {
  --my-custom-property: 'initial';
}

.item:hover {
  --my-custom-property: 'hovering';
}
.item::before {
  content: var(--my-custom-property);
  font-size: 2rem;
}

.item.sticky {
    /* https://stackoverflow.com/questions/25308823/targeting-positionsticky-elements-that-are-currently-in-a-stuck-state/79471060#79471060 */
    container-type: scroll-state;
    position: sticky;
    top: 0;
}
@container scroll-state(stuck: top) {
    .item.sticky > p {
        --my-custom-property: 'stuck';
    }
    .item.sticky > p::before {
      content: var(--my-custom-property);
      font-size: 2rem;
    }
}

```
```js
import StyleObserver from "https://cdn.jsdelivr.net/npm/style-observer@0.1.1/+esm";
const observer = new StyleObserver(console.log);
observer.observe(document.querySelectorAll(".item, .item > p"), "--my-custom-property");
```

If we delete lines
```css
.item, .item.sticky > p {
  --my-custom-property: 'initial';
}
```
from CSS, the observe callback will never trigger.

**Comment by DmitrySharabin** [comment]
Okay, here is what we have. In Style Observer, if a custom property (e.g., `--foo`) is not registered explicitly, and the browser is affected by the [unregistered property transition bug](https://issues.chromium.org/issues/360159391), we register it as follows:

```css
@property --foo {
  syntax: "*";
  inherits: true;
}
```

This allows us to observe the property changes.

However, as it turned out, this is not enough. Suppose the property is updated on hover or in a container query rule (not all, probably in the new ones, like `@container scroll-state()`; we have [tests](http://127.0.0.1:5500/tests/?test=change) where the changes are correctly observed) and _it doesn't have an initial value_ (set in some other CSS rule). In that case, the transition events are **not fired**, and we can't observe the property changes.

Reduced testcase: https://codepen.io/dmitrysharabin/pen/xbGPVmE?editors=1111

Safari doesn't seem affected by this bug.

As a possible fix, I'd suggest assigning the property an initial value (one that won't break the author's code, if we have any). Something like that:

```css
@property --foo {
  syntax: "*";
  inherits: true;
  initial-value: "";
}
```

@LeaVerou, what do you think? I think @ n0099 pointed out another browser bug for us to consider.
